# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- task: ArchiveFiles@2
  displayName: "File Archive Task"
  inputs:
    rootFolderOrFile: '$(Build.BinariesDirectory)'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true

- task: SonarCloudPrepare@1
  displayName: "Sonarcloud Prepare Task"
  inputs:
    SonarCloud: 'SonarCloud Connection'
    organization: 'salihavci'
    scannerMode: 'MSBuild'
    projectKey: 'salihavci_xUnitNetCore'
    projectName: 'xUnitNetCore'
- task: DotNetCoreCLI@2
  displayName: "Dotnet Restore Task"
  inputs:
    command: 'restore'
    projects: '**/*.csproj'
    feedsToUse: 'select'
    
- task: DotNetCoreCLI@2
  displayName: "Dotnet Build Task"
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: "Dotnet Test Task"
  inputs:
    command: test
    projects: 'xUnitNetCore.Test/*.csproj'
    arguments: '--configuration $(buildConfiguration) --collect "Code coverage"'

- task: SonarCloudAnalyze@1
  displayName: "Sonarcloud Run Analyze Task"
  inputs:
    jdkversion: 'JAVA_HOME_17_X64'

- task: SonarCloudPublish@1
  displayName: "Sonarcloud Publish Task"
  inputs:
    pollingTimeoutSec: '300'
- task: DotNetCoreCLI@2
  displayName: "Dotnet Publish Task"
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: false
    
- task: PublishBuildArtifacts@1
  displayName: "Publish Build Artifacts"
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'paketTestProje'
    publishLocation: 'Container'